; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "FileORZ"
#define MyAppVersion "{{VERSION}}"
#define MyAppPublisher "Dev: Katchan"
#define MyAppURL "https://thainanviniciuskatchan.github.io/FileORZ/"
#define MyAppExeName "FL_ORZ.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{717F93AA-BFA2-41E6-9FF9-6792F4D7933F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir={#GetEnv('USERPROFILE')}\Desktop
OutputBaseFilename=FileORZ_install_{{VERSION}}
SetupIconFile={#GetEnv('USERPROFILE')}\Desktop\FileORZ\ui\icon\IconApp.ico
SolidCompression=yes
WizardStyle=modern dark

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
[Files]
Source: "dist\config.json"; DestDir: "{app}\dist"; Flags: uninsneveruninstall onlyifdoesntexist
Source: "dist\Key_Words.json"; DestDir: "{app}\dist"; Flags: uninsneveruninstall onlyifdoesntexist

Source: "{#GetEnv('USERPROFILE')}\Desktop\FileORZ\FileORZ\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#GetEnv('USERPROFILE')}\Desktop\FileORZ\FileORZ\*"; DestDir: "{app}"; Excludes: "dist\config.json,dist\Key_Words.json"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  ConfigOrigem, KeyWordsOrigem, ConfigBackup, KeyWordsBackup: string;
begin
  { Mapeia os caminhos originais e os caminhos do backup na pasta temporária }
  ConfigOrigem := ExpandConstant('{app}\dist\config.json');
  KeyWordsOrigem := ExpandConstant('{app}\dist\Key_Words.json');
  ConfigBackup := ExpandConstant('{tmp}\config.json');
  KeyWordsBackup := ExpandConstant('{tmp}\Key_Words.json');

  { Ocorre ANTES de começar a extrair os arquivos novos }
  if CurStep = ssInstall then
  begin
    if FileExists(ConfigOrigem) then 
      FileCopy(ConfigOrigem, ConfigBackup, False);
      
    if FileExists(KeyWordsOrigem) then 
      FileCopy(KeyWordsOrigem, KeyWordsBackup, False);
  end
  
  { Ocorre DEPOIS que tudo foi instalado }
  else if CurStep = ssPostInstall then
  begin
    if FileExists(ConfigBackup) then 
      FileCopy(ConfigBackup, ConfigOrigem, False);
      
    if FileExists(KeyWordsBackup) then 
      FileCopy(KeyWordsBackup, KeyWordsOrigem, False);
  end;
end;